### ISSUE TITLE
Device request/build instruction request: Samsung Galaxy M20 (m20lte)

### ISSUE THREAD

**Issue by finalsecure** [crdroidandroid/local_manifests#87]
Can you create crDroid 14.1 installation zip for Samsung Galaxy M20 or provide an instruction on how to create it? I follow your project with interest and want to install it on my device and try it.

Some resources that I think might be helpful regarding the kernel/vendor I have:
https://github.com/SamarV-121/android_device_samsung_m20lte
https://github.com/SamarV-121/android_device_samsung_universal7904-common
https://github.com/SamarV-121/android_kernel_samsung_universal7904
https://github.com/SamarV-121/proprietary_vendor_samsung

**Comment by gwolf2u** [comment]
this page should get you started
https://github.com/crdroidandroid/android/blob/14.0/README.mkdn

device side changes need to be cloned via dependencies file or manifest (or even manually, but that's non-standard)
good luck
